import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import { Toaster } from "sonner";

const inder = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Task APp",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inder.className} mt-10`}>
                <Providers>
                    <main className="max-w-5xl m-auto text-center">{children}</main>
                    <Toaster richColors position="top-right" closeButton />
                </Providers>
            </body>
        </html>
    );
}
